baseurl: "" # the subpath of your site, e.g. /blog
url: "https://thecoldestride.com" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
markdown: kramdown
exclude:
  - Gemfile
  - Gemfile.lock

sass:
  style: compressed
  sass_dir: _scss

# First language in the list is default
languages: ["en", "lt"]
exclude_from_localizations: ["css", "fonts", "images"]

forms:
  contact: https://formspree.io/karolis@thecoldestride.com
  newsletter: https://thecoldestride.us19.list-manage.com/subscribe/post?u=63a300643885f0ff16e144794&amp;id=9fa6dba6cd

analytics:
  ga:
    id: UA-125482278-1
  fb:
    id: 255381175139812
